# Generated by Django 4.0.6 on 2023-05-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coralreef',
            old_name='latitude',
            new_name='latitudeC',
        ),
        migrations.RenameField(
            model_name='coralreef',
            old_name='longitude',
            new_name='longitudeC',
        ),
    ]
