# Generated by Django 4.0.6 on 2023-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0003_alter_coralreef_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coralreef',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coralreef',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
