# Generated by Django 4.0.6 on 2023-05-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapApp', '0004_alter_coralreef_description_alter_coralreef_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coralreef',
            name='observer',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
