# Generated by Django 4.0.6 on 2023-05-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0005_coralreef_observer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coralreef',
            name='observer',
        ),
    ]
