# Generated by Django 4.0.6 on 2023-05-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0006_remove_coralreef_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coralreef',
            name='observer_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
